//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omnioEntities : DbContext
    {
        public omnioEntities()
            : base("name=omnioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_BriolerData> tbl_BriolerData { get; set; }
        public DbSet<tbl_Briolers> tbl_Briolers { get; set; }
        public DbSet<tbl_BroilerInfo> tbl_BroilerInfo { get; set; }
        public DbSet<tbl_CullsEvent> tbl_CullsEvent { get; set; }
        public DbSet<tbl_DeviceData> tbl_DeviceData { get; set; }
        public DbSet<tbl_DeviceDataDetail> tbl_DeviceDataDetail { get; set; }
        //public DbSet<tbl_DeviceDataDetailGetLatest> tbl_DeviceDataDetailGetLatest { get; set; }
        //public DbSet<tbl_DeviceLimitsGetLatest> tbl_DeviceLimitsGetLatest { get; set; }
        public DbSet<tbl_DeviceLimits> tbl_DeviceLimits { get; set; }
        public DbSet<tbl_Devices> tbl_Devices { get; set; }
        public DbSet<tbl_DeviceType> tbl_DeviceType { get; set; }
        public DbSet<tbl_Farm> tbl_Farm { get; set; }
        public DbSet<tbl_FeedWater> tbl_FeedWater { get; set; }
        public DbSet<tbl_Hatchery> tbl_Hatchery { get; set; }
        public DbSet<tbl_MortalitiesEvent> tbl_MortalitiesEvent { get; set; }
        public DbSet<tbl_ThresholdAlarms> tbl_ThresholdAlarms { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
        public DbSet<tbl_UsersAdditional> tbl_UsersAdditional { get; set; }
        public DbSet<tbl_UserTypes> tbl_UserTypes { get; set; }
        public DbSet<tbl_Weights> tbl_Weights { get; set; }
        public DbSet<vw_briolerDataDay> vw_briolerDataDay { get; set; }
        public DbSet<vw_briolerDataMonth> vw_briolerDataMonth { get; set; }
        public DbSet<vw_briolerDataWeek> vw_briolerDataWeek { get; set; }
        public DbSet<vw_DeviceDetails> vw_DeviceDetails { get; set; }
        public DbSet<tbl_Cycles> tbl_Cycles { get; set; }
        public DbSet<tbl_PlacementWeight> tbl_PlacementWeight { get; set; }
        public DbSet<tbl_BroilerSettings> tbl_BroilerSettings { get; set; }
        public DbSet<tbl_Feed> tbl_Feed { get; set; }
        public DbSet<tbl_catching> tbl_catching { get; set; }
        public DbSet<tbl_activities> tbl_activities { get; set; }
        public DbSet<tbl_DOC> tbl_DOC { get; set; }
        public DbSet<tbl_DOCTable> tbl_DOCTable { get; set; }
        public DbSet<tbl_Health> tbl_Health { get; set; }
        public DbSet<tbl_Systems> tbl_Systems { get; set; }
    }
}
