//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Briolers
    {
        public tbl_Briolers()
        {
            this.tbl_BriolerData = new HashSet<tbl_BriolerData>();
            this.tbl_Devices = new HashSet<tbl_Devices>();
            this.tbl_Cycles = new HashSet<tbl_Cycles>();
            this.tbl_DOC = new HashSet<tbl_DOC>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> farmID { get; set; }
        public Nullable<int> NoOfBirds { get; set; }
    
        public virtual ICollection<tbl_BriolerData> tbl_BriolerData { get; set; }
        public virtual ICollection<tbl_Devices> tbl_Devices { get; set; }
        public virtual ICollection<tbl_Cycles> tbl_Cycles { get; set; }
        public virtual ICollection<tbl_DOC> tbl_DOC { get; set; }
    }
}
