//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Feed
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> stageId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> feedname { get; set; }
        public Nullable<double> weight { get; set; }
    }
}
