//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FeedWater
    {
        public int ID { get; set; }
        public Nullable<int> broilerID { get; set; }
        public Nullable<double> Feed { get; set; }
        public Nullable<double> WaterConsumption { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> cycleId { get; set; }
    }
}
