//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Health
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> litterId { get; set; }
        public Nullable<int> sanitationId { get; set; }
        public Nullable<int> healthId { get; set; }
        public Nullable<int> vaccinationId { get; set; }
    }
}
