//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activities
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> typeAct { get; set; }
        public Nullable<int> nameId { get; set; }
        public double dosage { get; set; }
        public string addremove { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string response_1 { get; set; }
        public string response_2 { get; set; }
        public string response_3 { get; set; }
        public string response_4 { get; set; }
        public string sid_1 { get; set; }
        public string sid_2 { get; set; }
        public string sid_3 { get; set; }
        public string sid_4 { get; set; }
        public Nullable<System.DateTime> dt_response_1 { get; set; }
        public Nullable<System.DateTime> dt_response_2 { get; set; }
        public Nullable<System.DateTime> dt_response_3 { get; set; }
        public Nullable<System.DateTime> dt_response_4 { get; set; }
    }
}
