//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DOC
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> hatcheryName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string invoiceNumber { get; set; }
        public Nullable<int> totalNoOfBoxes { get; set; }
        public Nullable<int> noOfBirdsPerBox { get; set; }
        public Nullable<int> totalQauntity { get; set; }
        public Nullable<int> breederCode { get; set; }
        public string description { get; set; }
        public Nullable<double> checkWeight { get; set; }
        public Nullable<int> qauntity { get; set; }
        public Nullable<int> parentAge { get; set; }
        public Nullable<System.DateTime> timeOfPulling { get; set; }
        public Nullable<int> hatcherNo { get; set; }
        public Nullable<int> setterNo { get; set; }
        public Nullable<int> noOfBirdsInBoxes { get; set; }
        public Nullable<double> internalChickTemp { get; set; }
        public Nullable<double> vehicleRelativeHumidity { get; set; }
        public Nullable<double> cargoHoldTemp { get; set; }
        public Nullable<double> boxStockDensity { get; set; }
        public Nullable<double> holdingAreaTemp { get; set; }
        public string primaryNumber { get; set; }
        public string secondaryNumber { get; set; }
        public Nullable<System.DateTime> timeOfDelivery { get; set; }
    }
}
