//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PlacementWeight
    {
        public int id { get; set; }
        public Nullable<double> totalBirdWeight { get; set; }
        public Nullable<double> averageBox { get; set; }
        public Nullable<int> noOfBoxes { get; set; }
        public Nullable<int> noOfBirdsPerBox { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<long> weightId { get; set; }
    }
}
