//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TestSync
    {
        public System.Guid ID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public byte[] SyncStamp { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public byte[] Image { get; set; }
    }
}
