//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BroilerSettings
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<System.DateTime> placementDate { get; set; }
        public Nullable<int> heatingSystemsType { get; set; }
        public Nullable<int> ventalationSystem { get; set; }
        public Nullable<int> drinkerSystemType { get; set; }
        public Nullable<int> lightingProgram { get; set; }
        public Nullable<int> litterType { get; set; }
        public Nullable<int> healthType { get; set; }
        public Nullable<int> sanitationProgram { get; set; }
        public Nullable<System.DateTime> dateFinalCatch { get; set; }
        public Nullable<int> vaccination { get; set; }
        public Nullable<int> strain { get; set; }
    }
}
