//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Systems
    {
        public int id { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> heatingId { get; set; }
        public Nullable<int> ventilationId { get; set; }
        public Nullable<int> drinkerId { get; set; }
        public Nullable<int> lightingId { get; set; }
    }
}
