//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceData
    {
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> AirTemp { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> CO2 { get; set; }
        public Nullable<double> NH3 { get; set; }
        public Nullable<double> Water { get; set; }
        public Nullable<double> WaterTemp { get; set; }
        public Nullable<double> ORP { get; set; }
        public Nullable<double> EC { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Battery { get; set; }
        public Nullable<double> Lux { get; set; }
    
        public virtual tbl_Devices tbl_Devices { get; set; }
    }
}
