//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DOCTable
    {
        public int id { get; set; }
        public Nullable<int> cycleId { get; set; }
        public Nullable<int> breederCode { get; set; }
        public string description { get; set; }
        public Nullable<float> chickWeight { get; set; }
        public Nullable<int> qauntity { get; set; }
        public Nullable<int> parentAge { get; set; }
        public Nullable<System.DateTime> timeOfPulling { get; set; }
        public Nullable<int> hatcherno { get; set; }
        public Nullable<int> setterno { get; set; }
        public Nullable<int> broilerId { get; set; }
        public Nullable<int> deformaties { get; set; }
    }
}
