//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Farm
    {
        public tbl_Farm()
        {
            this.tbl_Briolers = new HashSet<tbl_Briolers>();
            this.tbl_Cycles = new HashSet<tbl_Cycles>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_Briolers> tbl_Briolers { get; set; }
        public virtual ICollection<tbl_Cycles> tbl_Cycles { get; set; }
    }
}
