//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceLimits
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<long> DeviceDataID { get; set; }
        public string Unit { get; set; }
        public Nullable<double> HighLimit { get; set; }
        public Nullable<double> LowLimit { get; set; }
        public string HighColor { get; set; }
        public string LowColor { get; set; }
        public string SetpointColor { get; set; }
        public Nullable<bool> ThresholdEnabled { get; set; }
        public string PrimaryContact { get; set; }
        public string SecondaryContact { get; set; }
        public Nullable<int> SecondaryContactDelay { get; set; }
        public string DeviceType { get; set; }
        public Nullable<int> smsDelay { get; set; }
    
        public virtual tbl_DeviceDataDetail tbl_DeviceDataDetail { get; set; }
        public virtual tbl_Devices tbl_Devices { get; set; }
        public virtual tbl_ThresholdAlarms tbl_ThresholdAlarms { get; set; }
    }
}
