//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceType
    {
        public tbl_DeviceType()
        {
            this.tbl_Devices = new HashSet<tbl_Devices>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> AirTemp { get; set; }
        public Nullable<bool> Humidity { get; set; }
        public Nullable<bool> PH { get; set; }
        public Nullable<bool> CO2 { get; set; }
        public Nullable<bool> NH3 { get; set; }
        public Nullable<bool> WaterTemp { get; set; }
        public Nullable<bool> ORP { get; set; }
        public Nullable<bool> EC { get; set; }
        public Nullable<bool> Weight { get; set; }
        public Nullable<bool> Battery { get; set; }
    
        public virtual ICollection<tbl_Devices> tbl_Devices { get; set; }
    }
}
