//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BriolerData
    {
        public int ID { get; set; }
        public Nullable<int> briolerID { get; set; }
        public Nullable<int> fatalities { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<int> culls { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> eventCullsID { get; set; }
        public Nullable<int> eventMortalitiesID { get; set; }
    
        public virtual tbl_CullsEvent tbl_CullsEvent { get; set; }
        public virtual tbl_MortalitiesEvent tbl_MortalitiesEvent { get; set; }
    }
}
