//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserTypes
    {
        public tbl_UserTypes()
        {
            this.tbl_Users = new HashSet<tbl_Users>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> Rights { get; set; }
    
        public virtual ICollection<tbl_Users> tbl_Users { get; set; }
    }
}
