//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Weights
    {
        public long ID { get; set; }
        public Nullable<int> BroilerID { get; set; }
        public Nullable<double> WeightBack { get; set; }
        public Nullable<double> WeightCenter { get; set; }
        public Nullable<double> WeightFront { get; set; }
        public Nullable<double> WeightAverage { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<double> WeightBackR { get; set; }
        public Nullable<double> WeightCenterR { get; set; }
        public Nullable<double> WeightFrontR { get; set; }
        public Nullable<double> SampleSize { get; set; }
    
        public virtual tbl_Briolers tbl_Briolers { get; set; }
    }
}
