//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceDataDetail
    {
        public tbl_DeviceDataDetail()
        {
            this.tbl_DeviceLimits = new HashSet<tbl_DeviceLimits>();
        }
    
        public long ID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> TImestamp { get; set; }
        public Nullable<double> Value { get; set; }
        public string ValueType { get; set; }
        public string Unit { get; set; }
    
        public virtual tbl_Devices tbl_Devices { get; set; }
        public virtual ICollection<tbl_DeviceLimits> tbl_DeviceLimits { get; set; }
    }
}
