//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Devices
    {
        public tbl_Devices()
        {
            this.tbl_DeviceDataDetail = new HashSet<tbl_DeviceDataDetail>();
            this.tbl_DeviceLimits = new HashSet<tbl_DeviceLimits>();
        }
    
        public string DeviceID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> BriolerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_DeviceData tbl_DeviceData { get; set; }
        public virtual ICollection<tbl_DeviceDataDetail> tbl_DeviceDataDetail { get; set; }
        public virtual ICollection<tbl_DeviceLimits> tbl_DeviceLimits { get; set; }
        public virtual tbl_DeviceType tbl_DeviceType { get; set; }
    }
}
