//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_briolerDataDay
    {
        public Nullable<int> Total { get; set; }
        public Nullable<int> TotalCulls { get; set; }
        public Nullable<double> AvgWeight { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public int ID { get; set; }
    }
}
