//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DeviceDetails
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string BriolerName { get; set; }
        public string BriolerDescription { get; set; }
        public string FarmName { get; set; }
        public string FarmDescription { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> TImestamp { get; set; }
        public string Unit { get; set; }
    }
}
