//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cb_LiveData : DbContext
    {
        public cb_LiveData()
            : base("name=cb_LiveData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_DeviceData> tbl_DeviceData { get; set; }
        public DbSet<tbl_DeviceDataDetail> tbl_DeviceDataDetail { get; set; }
        public DbSet<tbl_DeviceLimits> tbl_DeviceLimits { get; set; }
        public DbSet<tbl_Devices> tbl_Devices { get; set; }
        public DbSet<tbl_DeviceType> tbl_DeviceType { get; set; }
        public DbSet<tbl_ThresholdAlarms> tbl_ThresholdAlarms { get; set; }
    }
}
